#!/bin/sh

#{{{ MEMORY

while IFS=":" read -r a b; do
	case "$a" in
		"MemTotal") mem_used="$((mem_used+=${b/kB}))"; mem_total="${b/kB}" ;;
		"Shmem") mem_used="$((mem_used+=${b/kB}))"  ;;
		"MemFree" | "Buffers" | "Cached" | "SReclaimable")
			mem_used="$((mem_used-=${b/kB}))"
		;;
	esac
done < /proc/meminfo

mem_used="$((mem_used / 1024))"
mem_total="$((mem_total / 1024))"
memory="${mem_used}${mem_label:-MiB} / ${mem_total}${mem_label:-MiB}"
#}}}

#{{{ UPTIME

strip_date() {
        case "$1" in
        	"0 "*) unset "${1/* }" ;;
                "1 "*) printf "%s" "${1/s}" ;;
                *)     printf "%s" "$1" ;;
	esac
}

seconds=`< /proc/uptime`
seconds="${seconds/.*}"
days="$((seconds / 60 / 60 / 24)) days"
hours="$((seconds / 60 / 60 % 24)) hours"
mins="$((seconds / 60 % 60)) minutes"

days="$(strip_date "$days")"
hours="$(strip_date "$hours")"
mins="$(strip_date "$mins")"

uptime="${days:+$days, }${hours:+$hours, }${mins}"
uptime="${uptime%', '}"
uptime="${uptime:-${seconds} seconds}"

uptime="${uptime/ days/d}"
uptime="${uptime/ day/d}"
uptime="${uptime/ hours/h}"
uptime="${uptime/ hour/h}"
uptime="${uptime/ minutes/m}"
uptime="${uptime/ minute/m}"
uptime="${uptime/ seconds/s}"

uptime="${uptime//,}"

#}}}

#{{{ GPU

gpu="$(glxinfo | grep -F 'OpenGL renderer string')"
gpu="${gpu/'OpenGL renderer string: '}"
gpu="${gpu/(*}"

#}}}

#{{{ SYSTEM

kernel=`uname -r`
# | cut -d'-' -f1
operating=`uname -o`
cpuspe="`sed -n '/model\ name/s/^.*:\ //p' /proc/cpuinfo | uniq` (x`nproc`)"

system=`lsb_release -si`
arch=`uname -m`
kname=`uname -s`

#pkgnum=`ls -d /var/lib/eopkg/package/* | wc -l`
pkgnum=`pacman -Q | wc -l`

birthd=`last | grep "begins" | sed 's/wtmp begins //g'`
#}}}

#{{{ ENVIROMENT

if [ -n "$DISPLAY" ]; then
    wmname=`xprop -root _NET_WM_NAME|cut -d\" -f2`
    termfn=`xrdb -query | grep .font | cut -d':' -f3 | head -1`
    termfs=`xrdb -query | grep .font | cut -d':' -f4 | head -1 | cut -d'=' -f2` 
    systfn=`sed -n 's/^.*font.*"\(.*\)".*$/\1/p' ~/.gtkrc-2.0`
    res=`xrandr --nograb --current | grep 'primary' | awk '{print $4}' | cut -d' ' -f3 | sed 's/+0+0//g'`
else
    wmname="none"
    termfn="none"
    systfn="none"
fi

#}}}

c00=$'\e[0;30m'
c01=$'\e[0;31m'
c02=$'\e[0;32m'
c03=$'\e[0;33m'
c04=$'\e[0;34m'
c05=$'\e[0;35m'
c06=$'\e[0;36m'
c07=$'\e[0;37m'
c08=$'\e[1;30m'
c09=$'\e[1;31m'
c10=$'\e[1;32m'
c11=$'\e[1;33m'
c12=$'\e[1;34m'
c13=$'\e[1;35m'
c14=$'\e[1;36m'
c15=$'\e[1;37m'

f0=$'\e[1;30m'
f1=$'\e[1;37m'
f2=$'\e[0;37m'

cat << EOF
${c01}▉▉  | ${f1}System ${f0}....... $f2$system/$kname $f2$arch
${c09}  ▉▉| ${f1}Packages ${f0}..... $f2$pkgnum
${c07}▉▉  | ${f1}Uptime  ${f0}...... $f2$uptime
${c15}  ▉▉| ${f1}Resolution  ${f0}.. $f2$res, $f2$res
${c02}▉▉  |
${c10}  ▉▉| ${f1}WM ${f0}........... $f2$wmname
${c03}▉▉  | ${f1}Shell ${f0}........ $f2$SHELL
${c11}  ▉▉| ${f1}Terminal ${f0}..... $f2$TERM
${c04}▉▉  | ${f1}Term Font ${f0}.... $f2$termfn $f2$termfs
${c12}  ▉▉| ${f1}System Font ${f0}.. $f2$systfn
${c05}▉▉  | 
${c13}  ▉▉| ${f1}Kernel ${f0}....... $f2$kernel $f2$operating
${c06}▉▉  | ${f1}Processor ${f0}.... $f2$cpuspe
${c14}  ▉▉| ${f1}Gpu ${f0}.......... $f2$gpu
${c07}▉▉  |
${c15}  ▉▉| ${f1}Birthday ${f0}..... $f2$birthd
${c08}▉▉  | ${f1}Memory ${f0}....... $f2$memory

EOF
