#!/usr/bin/env bash

if [ $# -eq 3 ]; then
	ffmpeg -v warning -ss 18 -t 20 -i "$1" -vf scale="$3":-1 -gifflags -transdiff -y "$2"

else
	echo "must enter video file, output gif and width (scale) arguments"
	echo ""
	echo "EXAMPLE:"
	echo "        convertgif ~/Videos/sample.mp4 ~/output.gif 800"
fi