#!/usr/bin/env bash

#sh $HOME/.config/lemonbar/run_lemonbar2.sh &
RESULT=$(sh /home/pheonix/.checksession)

if [[ "$RESULT" == "" ]];then
	sh $HOME/.config/lemonbar/run_lemonbar2.sh &
else
	sh $HOME/.config/lemonbar/run_lemonbar.sh &
fi

exit
